ackarma/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls

urlpatterns = [
    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^account/', include('accounts.urls')),
    url(r'^', include('subscriptions.urls')),
    url(r'^', include(wagtail_urls)),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

subscriptions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r'^dashboard/',
        views.dashboard,
        name='dashboard'
    ),
    url(
        r'^subscriptions/',
        views.user_subscriptions,
        name='user_subscriptions'
    ),
    url(
        r'^push_notifications/',
        views.push_notifications,
        name='push_notifications'
    ),
    url(
        r'^billing_info/',
        views.billing_information,
        name='billing_information'
    ),
    url(
        r'^subscription/(?P<plan_code>[\w-]+)',
        views.upgrade_subscription,
        name='upgrade_subscription'
    ),
]

subscriptions/models.py
import recurly
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.utils.text import slugify
from django.utils.dateformat import format as df
from django.core.validators import RegexValidator
from django.forms import CheckboxSelectMultiple, Select
from decimal import Decimal
from activecampaign import ActiveCampaign
from wagtail.wagtailadmin.edit_handlers import (
    FieldPanel, FieldRowPanel, MultiFieldPanel
)
from wagtail.wagtailsnippets.models import register_snippet
from wagtail.wagtailsnippets.edit_handlers import SnippetChooserPanel
from wagtail.wagtaildocs.edit_handlers import DocumentChooserPanel
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel


recurly.SUBDOMAIN = settings.RECURLY_SUBDOMAIN
recurly.API_KEY = settings.RECURLY_API_KEY
ac = ActiveCampaign()


@register_snippet
class Sport(models.Model):
    name = models.CharField(
        max_length=128,
        help_text=('Will be used to group subscriptions together, should be '
                   'a display friendly name')
    )

    panels = [
        FieldPanel('name'),
    ]

    def __str__(self):
        return '%s' % self.name


class Product(models.Model):
    DAILY = 'days'
    MONTHLY = 'months'
    DURATION_CHOICES = (
        (DAILY, 'Daily'),
        (MONTHLY, 'Monthly'),
    )

    DOLLAR_TO_CENTS = 100

    name = models.CharField(max_length=128)

    # Store the Recurly plan code in our db for lookups.
    # From recurly docs: https://dev.recurly.com/docs/create-plan
    # Max length, 50 chars, must be unique, and can only contain
    # the following: [a-z 0-9 @ - _ .]
    recurly_plan_code = models.CharField(
        max_length=50,
        unique=True,
        blank=False,  # We're using pre-populated fields here.
        validators=[
            RegexValidator(
                # ignore case, a-z, 0-9, @, literal -, _, and literal .
                regex=r'(?i)[a-z0-9@\-_\.]',
                message=('Code entered must only contain alphanumeric '
                         'characters, as well as @, -, _, and .')
            )
        ],
        verbose_name='Recurly Plan Code',
        help_text='Used to uniquely identify the product in recurly.'
    )

    # Billing cycle for the product plan. Valid values for recurly are
    # daily and monthly, so I use choices here.
    duration = models.CharField(
        max_length=24,
        choices=DURATION_CHOICES,
        help_text=('Choose whether this product is a monthly subscription '
                   'or a one day purchase.')
    )

    # Sport is used on several pages to group products for display.
    sport = models.ForeignKey(
        Sport,
        null=True,
        on_delete=models.SET_NULL,
        help_text='Used to group together products.'
    )

    # The price of the subscription, stored as a decimal field, but
    # converted to an integer in cents for storage on recurly.
    price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        default=Decimal('0.00'),
        help_text='Price of the product'
    )

    # We use a through model here because we want to store additional
    # info about the subscription.
    subscribed = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='Subscription'
    )

    # Upload an image for display on marketing screens.
    marketing_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
        help_text=('Displayed on a user\'s dashboard page, and in any'
                   'marketing messaging related to this product.')
    )

    list_id = models.IntegerField(
        blank=True,
        null=True,
        help_text='ActiveCampaign mailing list ID.'
    )

    template_id = models.IntegerField(
        blank=True,
        null=True,
        help_text='ActiveCampaign template to use when sending updates.'
    )

    panels = [
        FieldPanel('name'),
        SnippetChooserPanel('sport'),
        ImageChooserPanel('marketing_image'),
        MultiFieldPanel([
            FieldRowPanel([
                FieldPanel('duration', classname='col6'),
                FieldPanel('price', classname='col6'),
            ]),
        ], 'Price and Duration'),
    ]

    def is_daily(self):
        if self.duration == self.DAILY:
            return True

        return False

    def is_monthly(self):
        return not self.is_daily()

    def get_recurly_plan(self):
        return recurly.Plan.get(self.recurly_plan_code)

    def __str__(self):
        return '%s' % self.name

    def save(self, *args, **kwargs):
        # Get plan if already existant. If not, create a new plan.
        try:
            plan = self.get_recurly_plan()
            plan.name = self.name
        except recurly.NotFoundError:
            plan = recurly.Plan(
                plan_code=self.recurly_plan_code,
                name=self.name
            )

        # Create activecampaign list if none exists.
        if not self.list_id:
            list_name = '{} {}'.format(self.sport.name, self.name)

            payload = {
                'name': list_name,
                'subscription_notify': '',
                'unsubscription_notify': '',
                'to_name': 'Subscriber',
                'carboncopy': '',
                'stringid': slugify(list_name),
                'sender_name': 'AC Karma Sports',
                'sender_addr1': '1234 Fake Addr.',
                'sender_zip': '43230',
                'sender_city': 'Columbus',
                'sender_country': 'USA',
                'sender_url': 'http://ackarmasports.com/',
                'sender_reminder': ('Thanks for being a subscriber of our '
                                    '{} plan!').format(list_name)
            }

            try:
                json = ac.api('list_add', method='post', data=payload)
                self.list_id = json['id']
            except AttributeError as e:
                print(e)

        # Convert USD price into cents.
        amount_in_cents = recurly.Money(int(self.price * self.DOLLAR_TO_CENTS))
        plan.unit_amount_in_cents = amount_in_cents

        # Apply the selected duration (interval length defaults to 1)
        plan.interval_unit = self.duration
        plan.success_url = settings.RECURLY_SUCCESS_URL
        plan.cancel_url = settings.RECURLY_CANCEL_URL

        # Save the model and plan in recurly.
        plan.save()
        super(Product, self).save(*args, **kwargs)


class LineUp(models.Model):
    pdf = models.ForeignKey(
        'wagtaildocs.Document',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )

    date_uploaded = models.DateTimeField(
        verbose_name='Date Uploaded',
        default=timezone.now
    )

    date_email_sent = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name='Last Email Sent',
        help_text=('Auto-filled. Records the last time an update email was'
                   ' sent to subscribers for this specific line up')
    )

    products = models.ManyToManyField(Product)

    template_id = models.IntegerField(
        blank=True,
        null=True,
        help_text='ActiveCampaign template to use when sending updates.'
    )

    def products_list(self):
        return ', '.join([product.name for product in self.products.all()])

    products_list.verbose_name = 'List of Products'

    def get_templates():
        templates = []

        response = ac.api('message_template_list', params={
            'ids': 'all'
        })

        for k, v in response.items():
            try:
                template = (v['id'], v['name'],)
                templates.append(template)
            except AttributeError:
                pass
            except TypeError:
                pass

        return templates

    panels = [
        DocumentChooserPanel('pdf'),
        FieldPanel('date_uploaded'),
        FieldPanel('date_email_sent'),
        FieldPanel('products', widget=CheckboxSelectMultiple),
        FieldPanel(
            'template_id',
            widget=Select(
                choices=get_templates()
            )
        )
    ]

    def __str__(self):
        return '#{}'.format(self.pk)

    class Meta:
        verbose_name = 'Line Up'
        get_latest_by = 'date_uploaded'


class Subscription(models.Model):
    ACTIVE = 'active'
    CANCELED = 'canceled'
    FUTURE = 'future'
    EXPIRED = 'expired'

    STATE_CHOICES = (
        (ACTIVE, 'active',),
        (CANCELED, 'canceled',),
        (FUTURE, 'future',),
        (EXPIRED, 'expired',),
    )

    # Relations we use locally.
    product = models.ForeignKey(
        Product,
        related_name='product',
        help_text='The product this subscription is for.'
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        help_text='The user that owns this subscription.'
    )

    # Recurly Mirrored Fields:
    state = models.CharField(
        blank=False,
        null=False,
        max_length=64,
        choices=STATE_CHOICES
    )

    # We're not using UUIDField here because we're populating directly
    # from Recurly.
    uuid = models.CharField(
        max_length=128,
        db_index=True,
        help_text='Recurly uuid.',
        editable=False
    )

    activated_at = models.DateTimeField(
        default=timezone.now,
        verbose_name='Date Subscribed',
        help_text='Records the date this subscription became active.'
    )

    canceled_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name='Date Cancelled',
        help_text='Records the date this subscription was cancelled.'
    )

    expired_at = models.DateTimeField(
        null=True,
        blank=True,
        verbose_name='Date Expired',

subscriptions/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from activecampaign import ActiveCampaign


ac = ActiveCampaign()


class BillingInfoForm(forms.Form):
    first_name = forms.CharField(label='First Name', required=False)
    last_name = forms.CharField(label='Last Name', required=False)
    number = forms.CharField(label='Card Number', required=False)
    verification_value = forms.CharField(label='CVV', required=False)
    month = forms.CharField(label='Expiration Month', required=False)
    year = forms.CharField(label='Expiration Year', required=False)
    address1 = forms.CharField(label='Address', required=False)
    address2 = forms.CharField(label='Address Line 2', required=False)
    city = forms.CharField(label='City', required=False)
    state = forms.CharField(label='State', required=False)
    country = forms.CharField(label='Country', required=False)
    postal_code = forms.CharField(label='Zip Code', required=False)
    token = forms.CharField(widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super(BillingInfoForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = 'billing-information'
        self.helper.form_method = 'post'
        self.helper.form_action = 'billing_information'
        self.helper.add_input(Submit('save', 'Save Billing Info'))


class ProductAdminForm(forms.ModelForm):
    def get_choices():
        choices = []

        response = ac.api('message_template_list', params={
            'ids': 'all'
        })

        for k, v in response.items():
            try:
                choice = (v['id'], v['name'],)
                choices.append(choice)
            except AttributeError:
                pass
            except TypeError:
                pass

        return choices

    template_id = forms.ChoiceField(
        label='Template',
        required=False,
        choices=get_choices
    )

subscriptions/templates/subscriptions/billing_information.html
{% extends "accounts/base_accounts.html" %}
{% load staticfiles %}
{% csrf_token %}

{% block child_content %}
    <h3>Billing Information</h3>
    <form action="{% url 'billing_information' %}" method='POST' id='billing-information' name='billing-information'>
        {% csrf_token %}
        {% for field in form %}
            {% if field.html_name != 'token' %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}" class="control-label">{{ field.label }}</label>
                    <div class="controls">
                        <input
                            type="text"
                            id="{{ field.id_for_label }}"
                            class="textinput textInput form-control"
                            value="{% if field.value %}{{ field.value }}{% endif %}"
                            data-recurly="{{ field.html_name }}">
                    </div>
                </div>
            {% endif %}
        {% endfor %}
        <div class="form-group">
            <div class="controls">
                <input
                    type="hidden"
                    id="{{ form.token.id_for_label }}"
                    class="textinput textInput form-control"
                    value="{% if form.token.value %}{{ form.token.value }}{% endif %}"
                    data-recurly="{{ form.token.html_name }}"
                    name="{{ form.token.html_name }}">
            </div>
        </div>
        <div class="form-group">
            <div class="controls">
                <input
                    type="submit"
                    id="save"
                    value="Save Billing Information"
                    class="btn btn-primary"
                    name="save">
            </div>
        </div>
    </form>
{% endblock %}

{% block extra_js %}
    <script>
        (function () {
            $('form').on('submit', function (event) {
                var form = this;
                var form_elm = $('form');
                var token = $('#id_token').val();

                if (!token) {
                    event.preventDefault();
                    recurly.token(form, function (err, token) {
                        if (err) {
                            // handle error using err.code and err.fields
                            console.table(err);
                        } else {
                            form_elm.submit();
                        }
                    });
                }
            });
        })();
    </script>
{% endblock %}

subscriptions/templates/subscriptions/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}
{% load wagtailimages_tags %}

{% block content %}
    <div class="container">
        <div class="row">
            {% for group in lineups_by_date %}
                <div class="col-xs-12">
                    <h1>{{ group.date|date:'l, F j, Y' }}</h1>
                    {% for lineup in group.lineups %}
                        <a href="#" class="open-download-modal" data-target="{{ lineup.pdf.url }}">
                            {% if lineup.products.first.marketing_image %}
                                {% image lineup.products.first.marketing_image width-300 %}
                            {% else %}
                                <img src="{% static "images/nba_silver_large.png" %}">
                            {% endif %}
                        </a>
                    {% endfor %}
                </div>
            {% empty %}
                <div class="col-xs-12">
                    <h3>There are currently no lineups for you to view.</h3>
                    {% if user.subscription_set.count %}
                        <p>You have subscriptions, and will see your lineups on this page as they become available.</p>
                    {% else %}
                        <p>You are not currently subscribed to receive lineups. <a href="{% url 'user_subscriptions' %}">Subscribe now!</a></p>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block modal %}
    <div class="modal fade" tabindex="-1" role="dialog" id="download-modal">
          <div class="modal-dialog">
                <div class="modal-content">
                      <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title">Download PDF</h4>
                      </div>
                      <div class="modal-body">
                            <p>Are you sure you'd like to download this document.</p>
                      </div>
                      <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                            <button type="button" class="btn btn-primary" id="download-button">Yes</button>
                      </div>
                </div>
          </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        (function () {
            var path = '';

            function openDownloadModal (filePath) {
                path = filePath;
                $('#download-modal').modal('show');
            }

            function startDownload (filePath) {
                window.open(filePath, '_self');
                $('#download-modal').modal('hide');
            }

            $('#download-button').click(function () {
                startDownload(path);
            });

            $('.open-download-modal').click(function () {
                openDownloadModal($(this).data('target'));
            });
        })();
    </script>
{% endblock %}

subscriptions/templates/subscriptions/subscribe.html
{% extends "base.html" %}
{% load staticfiles %}
{% csrf_token %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3>Subscribe</h3>
                <form action="{% url 'upgrade_subscription' plan_code=plan_code %}" method='POST' id='upgrade_subscription' name='upgrade_subscription'>
                    {% csrf_token %}
                    {% for field in form %}
                        {% if field.html_name != 'token' %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}" class="control-label">{{ field.label }}</label>
                                <div class="controls">
                                    <input
                                        type="text"
                                        id="{{ field.id_for_label }}"
                                        class="textinput textInput form-control"
                                        value="{% if field.value %}{{ field.value }}{% endif %}"
                                        data-recurly="{{ field.html_name }}">
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="form-group">
                        <div class="controls">
                            <input
                                type="hidden"
                                id="{{ form.token.id_for_label }}"
                                class="textinput textInput form-control"
                                value="{% if form.token.value %}{{ form.token.value }}{% endif %}"
                                data-recurly="{{ form.token.html_name }}"
                                name="{{ form.token.html_name }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="controls">
                            <input
                                type="submit"
                                id="save"
                                value="Update Billing Information and Subscribe"
                                class="btn btn-primary"
                                name="save">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        (function () {
            $('form').on('submit', function (event) {
                var form = this;
                var form_elm = $('form');
                var token = $('#id_token').val();

                if (!token) {
                    event.preventDefault();
                    recurly.token(form, function (err, token) {
                        if (err) {
                            // handle error using err.code and err.fields
                            console.table(err);
                        } else {
                            form_elm.submit();
                        }
                    });
                }
            });
        })();
    </script>
{% endblock %}

subscriptions/templates/subscriptions/user_subscriptions.html
{% extends "accounts/base_accounts.html" %}
{% load staticfiles %}

{% block child_content %}
    <h3>Subscriptions</h3>
    <div class="row">
        {% for sport in subscriptions_by_sport %}
            <h4 class="text-center">{{ sport.name }}</h4>
            {% for value in sport.products %}
                {% if not value.product.is_daily %}
                    <div class="col-sm-4">
                        <div class="panel panel-default">
                            <div class="panel-body text-center">
                                <h5>{{ value.product.name }}</h5>
                                <p>${{ value.product.price }} monthly.</p>
                                <div class="button-wrapper">
                                    <div class="show open-confirm-change">
                                        {% if value.is_subscribed %}
                                            <button class="btn btn-primary">Current</button>
                                        {% else %}
                                            <button class="btn btn-default">{{ value.label }}</button>
                                        {% endif %}
                                    </div>
                                    <div class="hidden confirm-change">
                                        {% if sport.existing_subscription %}
                                            {% if value.is_subscribed %}
                                                <p>Cancel your Subscription?</p>
                                            {% else %}
                                                <p>{{ value.label }} your Subscription?</p>
                                            {% endif %}
                                        {% else %}
                                            <p>{{ value.label }} for this product? Your card on file will be immediately charged.</p>
                                        {% endif %}
                                        <form action="{% url 'upgrade_subscription' plan_code=value.product.recurly_plan_code %}" method="GET">
                                            <button class="btn btn-default" data-target="cancel">Cancel</button>
                                            <input
                                                class="btn btn-primary"
                                                value="Confirm"
                                                name="confirm"
                                                type="submit"
                                                id="{{ value.product.recurly_plan_code }}-confirm">
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        {% endfor %}
    </div>
{% endblock %}

{% block extra_js %}
    <script>
        (function () {
            function toggle(elemsToShow, elemsToHide) {
                elemsToHide.addClass('hidden').removeClass('show');
                elemsToShow.addClass('show').removeClass('hidden');
            }

            $('.open-confirm-change .btn').click(function () {
                var wrapper = $(this).parents('.button-wrapper');
                var toBeHidden = wrapper.children('.open-confirm-change');
                var toBeShown = wrapper.children('.confirm-change');

                // Hide all already open confirmations, only letting one be open at a time.
                toBeHidden = toBeHidden.add($('.confirm-change.show'));
                toBeShown = toBeShown.add($('.open-confirm-change.hidden'));

                toggle(toBeShown, toBeHidden);
            });

            $('.confirm-change .btn').click(function () {
                var target = $(this).data('target');

                if (target === 'cancel') {
                    var wrapper = $(this).parents('.button-wrapper');
                    var toBeShown = $('.open-confirm-change');
                    var toBeHidden = wrapper.children('.confirm-change');

                    toggle(toBeShown, toBeHidden);
                }
            });
        })();
    </script>
{% endblock %}